version: '3'

tasks:
  build:
    desc: Compila el proyecto y genera el binario en bin/
    cmds:
      - mkdir -p bin
      - go build -o bin/app .

  install:
    desc: Instala las dependencias del proyecto utilizando Go Modules
    cmds:
      - go mod download
      - go install gotest.tools/gotestsum@latest

  clean:
    desc: Elimina binarios y archivos generados
    cmds:
      - rm -rf bin

  check:
    desc: Verifica el formato y realiza análisis estático del código
    cmds:
      - go vet ./...
      - go build ./...
      
  test:
    desc: Ejecuta los tests unitarios de todo el proyecto
    env:
      GOCACHE: /tmp/gocache
      GOMODCACHE: /tmp/gomodcache
    deps: [install]
    cmds:
      - gotestsum --format short-verbose ./...
